# あいしす(仮)
#              Ver 1.1

# 合言葉を入れたら失敗にしたい場合はfalseにしてください
wordFlag: true

# 合言葉にしたいワードを入れる
word:
  - 'あいしす'
  - 'かなさき'
# 認証後どのグループ名にするか(PermissionExで設定したグループ名と同じにしてください)
nextPex:
  - 'default'